In [3]:
import numpy as np
import random

In [16]:
class TicTac:
    
    def __init__(self):
        
        self.state_size = 10
        self.action_size = 9
        self.state = np.zeros([10], dtype=int)
        self.state[9] = random.choice([-1, 1])
        self.done = False
        
    def step(self, action):
        player = self.state[9]
        
        if self.done:
            return np.copy(self.state), -10, True, {}
        
        if self.state[action] != 0:
            return np.copy(self.state), -10, False, {}
        
        self.state[action] = player
        
        done, reward = self.gen_reward()
        self.done = done
        self.state[9] = -player
        
        return np.copy(self.state), reward, done, {}
        
        
    def gen_reward(self):
        player = self.state[9]
        board = self.state[:-1].reshape(3, 3)
        
        rows = np.any(np.sum(board, axis=1) == player * 3)
        cols = np.any(np.sum(board, axis=0) == player * 3)
        d1 = np.sum(self.state[[0, 4, 8]]) == player * 3
        d2 = np.sum(self.state[[2, 4, 6]]) == player * 3
   
        if np.any([rows, cols, d1, d2]):
            return True, 10
        elif not np.any(self.state == 0):
            return True, 1     
        else:
            return False, 1
                

In [19]:
env = TicTac()

In [25]:
state, reward, done, info = env.step(1)
print(state[:-1].reshape(3, 3), state[-1], reward, done)

[[ 1  1  1]
 [-1  0  0]
 [-1  0  0]] -1 10 True


In [12]:
ab = np.array([4, 6, 7, 8])

In [14]:
ab[[1, 2]]

array([6, 7])