In [2]:
! python3 -m pip install numpy

In [1]:
! echo "hello"

hello


In [3]:
import numpy as np

In [4]:
arr = np.array([1,2, 4,6, 9])

In [5]:
arr

array([1, 2, 4, 6, 9])

In [6]:
type(arr)

numpy.ndarray

In [14]:
sec = np.array(range(10, 20, 2), dtype=np.int32)

In [15]:
sec

array([10, 12, 14, 16, 18], dtype=int32)

In [16]:
sec.dtype

dtype('int32')

In [18]:
data = np.arange(0, 20, 3)

In [22]:
data.shape

(7,)

In [23]:
data

array([ 0,  3,  6,  9, 12, 15, 18])

In [25]:
data.shape[0]

7

In [30]:
data = np.arange(20).reshape(10, 2)

In [31]:
data.dtype

dtype('int64')

In [32]:
data.shape

(10, 2)

In [36]:
another = np.arange(8).reshape(2, 4)

In [37]:
ekaur = another.reshape(4,2)

In [39]:
ekaur

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [43]:
data = np.zeros([4, 6], dtype=int)

In [44]:
data

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [45]:
data = np.ones([4, 6], dtype=int)

In [46]:
data

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [47]:
data.T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [49]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [51]:
np.linspace(0, 100, 5, dtype=int)

array([  0,  25,  50,  75, 100])

In [52]:
np.pi

3.141592653589793

In [54]:
x = np.linspace(0, 2*np.pi, 100)

In [55]:
np.sin(x)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [56]:
data = np.arange(20).reshape(5, 4)

## arithmatic

In [57]:
data + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [62]:
# data ** 10

In [64]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
data + np.arange(4)

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [68]:
data + np.arange(5).reshape(-1, 1)

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [70]:
img = np.zeros([100, 100])

In [71]:
second = np.linspace(0, 1, 10000).reshape(100, 100)

In [72]:
vals = np.sin(np.linspace(0, np.pi, 100))

In [73]:
second = img + vals

In [74]:
plt.imshow(second)

NameError: name 'plt' is not defined